### ISSUE TITLE
/root/global

### ISSUE THREAD

**Issue by OakBaker** [5FB5/gd-achievements#17] opened 2021-08-07 16:19 UTC
Error in console
Invalid get index 'achievements' (on base: 'null instance').

**Comment by 5FB5** [comment] 2021-08-07 16:21
I am aware of this error. I tested it and the plugin does not crash. so you can just ignore it. If you are satisfied with the answer, you can close the issue yourself :) This error can occur because during initial initialization it is unable to read the contents of the array, but it has no effect on the work of the plugin

**Comment by 5FB5** [comment] 2021-08-07 16:33
But ok, I'll try to fix it. Thanks!

**Comment by OakBaker** [comment] 2021-08-07 16:50
> I am aware of this error. I tested it and the plugin does not crash. so you can just ignore it. If you are satisfied with the answer, you can close the issue yourself :) This error can occur because during initial initialization it is unable to read the contents of the array, but it has no effect on the work of the plugin

no it does the game crashes

**Comment by OakBaker** [comment] 2021-08-07 16:53
also forgot the title the error changed
in achievement manger.gd
on line 22
onready var globalAchievements = get_node("/root/Global").achievements
gives an error

**Comment by 5FB5** [comment] 2021-08-07 16:53
What is your engine version?

**Comment by 5FB5** [comment] 2021-08-07 17:00
I've found a fix and will push it right now...

**Comment by 5FB5** [comment] 2021-08-07 17:06
I've added a fix to develop branch. You can download and replace "global.gd" script from "addons/gd-achievements/scripts/...". If your problem is fixed, you can close an issue by yourself :)

**Comment by 5FB5** [comment] 2021-08-08 10:39
It would be nice to let me know about this fix, 'cause after that I can publish this as update :)

**Comment by AI-Error-404** [comment] 2021-09-08 18:33
I ran across this error as well, there are two basic fixes for this. You can A.) add the global.gd that is included as an Autoload Singleton, or B.) if you already have a globals script just add var achievements = {} and then in the achievement_manager script change onready var globalAchievements = get_node("/root/Global").achievements to use your global script, for instance : onready var globalAchievements = GLOBALS.achievements

**Comment by 5FB5** [comment] 2021-09-08 18:34
Check develop branch for this fix plz

**Comment by realLiQ** [comment] 2021-09-09 17:31
Bug isnt fixed for me

**Comment by 5FB5** [comment] 2021-09-09 17:33
How you've reproduced this bug?

**Comment by realLiQ** [comment] 2021-09-09 17:33
idk

**Comment by realLiQ** [comment] 2021-09-09 17:34
i have the newest version

**Comment by 5FB5** [comment] 2021-09-09 17:34
![image](https://user-images.githubusercontent.com/15859698/132734580-cb26d125-80e2-4131-9ce1-b96ce0dd50ff.png)
My log is clear. Have you update a plugin? What Godot version is?

**Comment by realLiQ** [comment] 2021-09-09 17:35
![image](https://user-images.githubusercontent.com/69684095/132734846-d670677b-f0f8-4513-8ee9-a36092b5a1aa.png)

**Comment by realLiQ** [comment] 2021-09-09 17:37
Godot v3.3.3.stable

**Comment by 5FB5** [comment] 2021-09-09 17:39
![image](https://user-images.githubusercontent.com/15859698/132735328-69591b82-d92a-4822-a976-a398881e93ea.png)
On 3.3.3.stable

**Comment by realLiQ** [comment] 2021-09-09 17:40
¯\_(ツ)_/¯ idk whats wrong

**Comment by 5FB5** [comment] 2021-09-09 17:41
In fact, this error did not cause problems with the work of the plugin. Try to ignore it, but if critical errors occur, let me know

**Comment by realLiQ** [comment] 2021-09-09 17:41
critical error

**Comment by 5FB5** [comment] 2021-09-09 17:43
send me all scripts from addon, sorry

**Comment by realLiQ** [comment] 2021-09-09 17:46
do you have discord? github doesnt let me upload the .gd

**Comment by 5FB5** [comment] 2021-09-09 17:46
5FB5 #0417

**Closed as completed** 2021-09-09 18:13 UTC
Labels: bug
